name: Check Update

on:
  schedule:
    - cron: '0 */12 * * *'  # 毎時実行（調整可能）
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run check script
        env:
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
        run: python check.py

      - name: Commit state
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add last_hash.txt
          if ! git diff --cached --quiet; then
            git commit -m "Update hash"
            git push
          else
            echo "No changes to commit."
          fi